[build]
builder = "nixpacks"

[build.nixpacks]
providers = ["python"]

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p $PORT config.asgi:application"
