# Generated by Django 5.2.11 on 2026-04-10 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0002_onboarding_and_compliance'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='locations.location'),
        ),
        migrations.AddConstraint(
            model_name='staffassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('user', 'organization'), name='staff_assignment_unique_user_org_when_no_location'),
        ),
        migrations.AddConstraint(
            model_name='staffassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('user', 'location'), name='staff_assignment_unique_user_location_when_location_set'),
        ),
    ]
