# Generated by Django 5.2.13 on 2026-04-15 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_zone_table_zone'),
        ('orders', '0002_orderactivitylog'),
        ('organizations', '0005_organization_primary_color'),
        ('payments', '0001_initial'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='BillSplit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('equal', 'Split equally'), ('by_item', 'Split by item'), ('custom', 'Custom amounts')], default='equal', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_guests', models.PositiveIntegerField(default=2)),
                ('dining_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_splits', to='sessions_app.diningsession')),
            ],
            options={
                'db_table': 'orders_bill_split',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillSplitPortion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bill_split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='orders.billsplit')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_portions', to='payments.payment')),
            ],
            options={
                'db_table': 'orders_bill_split_portion',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='percentage', max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('locations', models.ManyToManyField(blank=True, related_name='discounts', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='organizations.organization')),
            ],
            options={
                'db_table': 'orders_discount',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.discount'),
        ),
    ]
