# Generated by Django 5.2.13 on 2026-04-15 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_organization_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('max_locations', models.PositiveIntegerField(default=1)),
                ('max_tables', models.PositiveIntegerField(default=10)),
                ('max_staff', models.PositiveIntegerField(default=3)),
                ('max_menus', models.PositiveIntegerField(default=1)),
                ('max_orders_per_month', models.PositiveIntegerField(default=500, help_text='0 = unlimited')),
                ('has_discounts', models.BooleanField(default=False)),
                ('has_bill_splitting', models.BooleanField(default=False)),
                ('has_online_payments', models.BooleanField(default=False)),
                ('has_full_reports', models.BooleanField(default=False)),
                ('has_custom_branding', models.BooleanField(default=False)),
                ('has_white_label', models.BooleanField(default=False)),
                ('allowed_payment_methods', models.JSONField(blank=True, default=list, help_text='e.g. ["cash","card_terminal","online"]')),
                ('online_payment_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Fee % on online transactions', max_digits=5)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlighted on pricing page')),
            ],
            options={
                'db_table': 'subscriptions_plan',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trialing', max_length=16)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=16)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('custom_overrides', models.JSONField(blank=True, default=dict, help_text='Override any plan limit for this org. Keys match Plan field names.')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'subscriptions_subscription',
            },
        ),
    ]
