# Generated by Django 5.2.13 on 2026-04-15 08:06

from django.db import migrations


def seed_plans(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")

    plans = [
        {
            "name": "Starter",
            "slug": "starter",
            "description": "Perfect for small cafés and single-location restaurants getting started with digital ordering.",
            "sort_order": 1,
            "monthly_price": 99,
            "annual_price": 1000,
            "currency": "TRY",
            "max_locations": 1,
            "max_tables": 10,
            "max_staff": 3,
            "max_menus": 1,
            "max_orders_per_month": 500,
            "has_discounts": False,
            "has_bill_splitting": False,
            "has_online_payments": False,
            "has_full_reports": False,
            "has_custom_branding": False,
            "has_white_label": False,
            "allowed_payment_methods": ["cash"],
            "online_payment_fee_percent": 0,
            "trial_days": 14,
            "is_active": True,
            "is_featured": False,
        },
        {
            "name": "Professional",
            "slug": "professional",
            "description": "For growing restaurants that need advanced features, multiple locations, and online payments.",
            "sort_order": 2,
            "monthly_price": 250,
            "annual_price": 2500,
            "currency": "TRY",
            "max_locations": 3,
            "max_tables": 0,
            "max_staff": 25,
            "max_menus": 10,
            "max_orders_per_month": 0,
            "has_discounts": True,
            "has_bill_splitting": True,
            "has_online_payments": True,
            "has_full_reports": True,
            "has_custom_branding": True,
            "has_white_label": False,
            "allowed_payment_methods": ["cash", "card_terminal", "online"],
            "online_payment_fee_percent": 1.5,
            "trial_days": 14,
            "is_active": True,
            "is_featured": True,
        },
        {
            "name": "Enterprise",
            "slug": "enterprise",
            "description": "Full-featured plan for restaurant chains and franchises with white-label support.",
            "sort_order": 3,
            "monthly_price": 1499,
            "annual_price": 15000,
            "currency": "TRY",
            "max_locations": 10,
            "max_tables": 0,
            "max_staff": 0,
            "max_menus": 0,
            "max_orders_per_month": 0,
            "has_discounts": True,
            "has_bill_splitting": True,
            "has_online_payments": True,
            "has_full_reports": True,
            "has_custom_branding": True,
            "has_white_label": True,
            "allowed_payment_methods": ["cash", "card_terminal", "online", "other"],
            "online_payment_fee_percent": 1.5,
            "trial_days": 14,
            "is_active": True,
            "is_featured": False,
        },
    ]

    for plan_data in plans:
        Plan.objects.update_or_create(slug=plan_data["slug"], defaults=plan_data)


def remove_plans(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    Plan.objects.filter(slug__in=["starter", "professional", "enterprise"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_plans, remove_plans),
    ]
