# Generated by Django 5.2.11 on 2026-04-06 15:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(default='TR', max_length=2)),
                ('timezone', models.CharField(default='Europe/Istanbul', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('tip_mode', models.CharField(choices=[('off', 'Off'), ('suggested', 'Suggested amounts'), ('customer_enters', 'Customer enters')], default='suggested', max_length=32)),
                ('tip_presets_percent', models.JSONField(default=list, help_text='e.g. [10, 15, 20] — admin-configured suggested tip percentages')),
                ('service_charge_enabled', models.BooleanField(default=False)),
                ('service_charge_apply', models.CharField(choices=[('off', 'Off'), ('dine_in', 'Dine-in only'), ('takeaway', 'Takeaway only'), ('delivery', 'Delivery only'), ('all', 'All channels')], default='dine_in', max_length=32)),
                ('service_charge_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.organization')),
            ],
            options={
                'db_table': 'locations_location',
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('map_x', models.FloatField(blank=True, null=True)),
                ('map_y', models.FloatField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='locations.location')),
            ],
            options={
                'db_table': 'locations_table',
                'ordering': ['sort_order', 'label'],
                'unique_together': {('location', 'label')},
            },
        ),
    ]
