# Generated by Django 5.2.13 on 2026-04-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='currency_code',
            field=models.CharField(default='TRY', max_length=3),
        ),
    ]
