# Generated by Django 5.2.13 on 2026-04-11 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='locations.location')),
            ],
            options={
                'db_table': 'locations_zone',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('location', 'name')},
            },
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='locations.zone'),
        ),
    ]
