# Generated by Django 5.2.11 on 2026-04-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_status',
            field=models.CharField(choices=[('pending_documents', 'Pending documents'), ('pending_review', 'Pending review'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('active', 'Active')], db_index=True, default='active', max_length=32),
        ),
    ]
