# Generated by Django 5.2.13 on 2026-04-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_onboarding_and_compliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='onboarding_status',
            field=models.CharField(choices=[('pending_documents', 'Pending documents'), ('pending_review', 'Pending review'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('active', 'Active')], db_index=True, default='pending_documents', max_length=32),
        ),
    ]
