# Generated by Django 5.2.13 on 2026-04-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_change_default_onboarding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
