# Generated by Django 5.2.13 on 2026-04-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Hex color e.g. #c45c26', max_length=7),
        ),
    ]
